/**
 * Panel Generator - generates individual panel images one by one.
 * 
 * Flow:
 * 1. Takes the full Grid image (generated by Gemini) as style/composition reference
 * 2. Takes Anchor images (character/scene) for consistency
 * 3. Generates each panel individually with a focused prompt
 * 4. Returns panel image URLs
 */

import { generateImage } from "./_core/imageGeneration";
import { logInfo, logError } from "./appLogger";

export interface PanelGenFrame {
  index: number;         // 1-based frame index
  shotType: string;
  duration: number;
  description: string;
  cameraMovement: string;
}

export interface PanelGenAnchor {
  anchorType: string;    // "character" | "scene"
  name: string;
  description: string | null;
  prompt: string | null;
  imageUrl: string | null;
}

export interface PanelGenCharacter {
  name: string;
  description: string;
  anchorPrompt?: string;
}

export interface PanelGenScene {
  name: string;
  description: string;
  anchorPrompt?: string;
}

export interface GeneratedPanel {
  frameIndex: number;    // 1-based
  imageUrl: string | null;
  prompt: string;
  error?: string;
}

/**
 * Generate a single panel image with retry support.
 * Uses character/scene anchor images as references (NOT the grid image).
 * The grid image is described in the prompt text only to avoid Gemini treating it as an edit target.
 */
export async function generateSinglePanel(opts: {
  frame: PanelGenFrame;
  localIndex: number;          // 1-based index within the page (1-6)
  totalPanelsInPage: number;   // total panels in this page
  gridImageUrl: string;        // Full grid image for style reference (used in prompt text only)
  anchors: PanelGenAnchor[];
  characters: PanelGenCharacter[];
  scenes: PanelGenScene[];
}): Promise<GeneratedPanel> {
  const { frame, localIndex, totalPanelsInPage, gridImageUrl, anchors, characters, scenes } = opts;
  let panelPrompt = '';

  try {
    // Build reference images - ONLY character and scene anchors
    // We do NOT pass the grid image as an originalImage to avoid Gemini treating it as an edit target
    const orderedImages: Array<{ url: string }> = [];
    const imageDescriptions: string[] = [];
    let imgIdx = 1;

    // Character anchor images
    const charAnchors = anchors.filter(a => a.anchorType === 'character' && a.imageUrl?.startsWith('http'));
    for (const ca of charAnchors) {
      orderedImages.push({ url: ca.imageUrl! });
      const charData = characters.find(c => c.name === ca.name);
      imageDescriptions.push(
        `Image #${imgIdx}: CHARACTER "${ca.name}" reference photo. The character in your generated image MUST look exactly like this person. ${ca.prompt || charData?.description || ca.description || ''}`
      );
      imgIdx++;
    }

    // Scene anchor images
    const sceneAnchors = anchors.filter(a => a.anchorType === 'scene' && a.imageUrl?.startsWith('http'));
    for (const sa of sceneAnchors) {
      orderedImages.push({ url: sa.imageUrl! });
      const sceneData = scenes.find(s => s.name === sa.name);
      imageDescriptions.push(
        `Image #${imgIdx}: SCENE "${sa.name}" reference photo. Use this as visual reference for the environment. ${sa.prompt || sceneData?.description || sa.description || ''}`
      );
      imgIdx++;
    }

    // Build character appearance block
    const charAppearanceLines = charAnchors.map(ca => {
      const charData = characters.find(c => c.name === ca.name);
      return `- "${ca.name}": ${ca.prompt || charData?.description || ca.description || 'See reference image'}`;
    }).join('\n');

    // Build the prompt - describe the grid context in text, not as an image
    panelPrompt = `${orderedImages.length > 0 ? `I am providing ${orderedImages.length} reference images:\n\n${imageDescriptions.join('\n')}\n\n` : ''}Generate a single high-resolution cinematic image based on the following description.

This image is Panel #${localIndex} of a ${totalPanelsInPage}-panel cinematic storyboard.

SCENE DESCRIPTION:
${frame.description}

SHOT DETAILS:
- Shot type: ${frame.shotType} (${getShotTypeDescription(frame.shotType)})
- Camera movement: ${frame.cameraMovement}
- Duration context: ${frame.duration}s

REQUIREMENTS:
1. Generate exactly ONE standalone cinematic image. Do NOT create a grid, collage, or multi-panel layout.
2. The characters MUST look EXACTLY like the reference photos provided — same face, same ethnicity, same hair, same clothing.
${charAppearanceLines ? `3. CHARACTER APPEARANCE:\n${charAppearanceLines}` : ''}

STYLE:
- A real photograph, NOT a digital render or CGI — shot on 35mm film, Kodak Vision3 500T
- Rich, saturated colors — avoid grey, washed-out, or desaturated palettes
- Real film texture: visible skin pores, natural hair strands, fabric wrinkles, dust particles
- Natural motivated lighting (practical lights, sunlight, neon) — NOT flat or overly even
- Aspect ratio: 16:9 landscape
- NO text, NO labels, NO watermarks, NO borders, NO panel numbers`;

    console.log(`[PanelGen] Generating panel ${localIndex}/${totalPanelsInPage} (Frame #${frame.index}): ${frame.shotType}`);

    const { url: imageUrl } = await generateImage({
      prompt: panelPrompt,
      originalImages: orderedImages.length > 0 ? orderedImages : undefined,
    });

    logInfo("panel_gen", `Panel ${localIndex} generated successfully`, {
      details: { frameIndex: frame.index, localIndex, shotType: frame.shotType, hasImage: !!imageUrl },
    }).catch(() => {});

    return {
      frameIndex: frame.index,
      imageUrl: imageUrl || null,
      prompt: panelPrompt,
    };
  } catch (e: any) {
    console.error(`[PanelGen] Panel ${localIndex} (Frame #${frame.index}) failed:`, e?.message || e);
    
    logError("panel_gen", `Panel ${localIndex} generation failed: ${e?.message}`, {
      details: { frameIndex: frame.index, localIndex, error: e?.message },
    }).catch(() => {});

    return {
      frameIndex: frame.index,
      imageUrl: null,
      prompt: panelPrompt,
      error: e instanceof Error ? e.message : String(e),
    };
  }
}

/**
 * Generate a single panel with retry logic.
 * Retries up to maxRetries times on failure (null imageUrl or error).
 */
async function generateSinglePanelWithRetry(opts: {
  frame: PanelGenFrame;
  localIndex: number;
  totalPanelsInPage: number;
  gridImageUrl: string;
  anchors: PanelGenAnchor[];
  characters: PanelGenCharacter[];
  scenes: PanelGenScene[];
  maxRetries?: number;
}): Promise<GeneratedPanel> {
  const { maxRetries = 2, ...panelOpts } = opts;
  
  let lastResult: GeneratedPanel | null = null;
  
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    if (attempt > 0) {
      console.log(`[PanelGen] Retrying panel ${panelOpts.localIndex} (attempt ${attempt + 1}/${maxRetries + 1})...`);
      // Wait before retry with exponential backoff
      await new Promise(r => setTimeout(r, 2000 * attempt));
    }
    
    const result = await generateSinglePanel(panelOpts);
    lastResult = result;
    
    // Success: got a valid image URL
    if (result.imageUrl) {
      if (attempt > 0) {
        console.log(`[PanelGen] Panel ${panelOpts.localIndex} succeeded on retry attempt ${attempt + 1}`);
        logInfo("panel_gen", `Panel ${panelOpts.localIndex} succeeded on retry attempt ${attempt + 1}`, {
          details: { frameIndex: panelOpts.frame.index, attempt: attempt + 1 },
        }).catch(() => {});
      }
      return result;
    }
    
    // Failed: log and continue to next attempt
    console.log(`[PanelGen] Panel ${panelOpts.localIndex} attempt ${attempt + 1} failed: ${result.error || 'no image returned'}`);
  }
  
  // All retries exhausted
  console.error(`[PanelGen] Panel ${panelOpts.localIndex} failed after ${maxRetries + 1} attempts`);
  logError("panel_gen", `Panel ${panelOpts.localIndex} failed after ${maxRetries + 1} attempts`, {
    details: { frameIndex: panelOpts.frame.index, lastError: lastResult?.error },
  }).catch(() => {});
  
  return lastResult!;
}

/**
 * Generate all panels for a grid page in parallel with concurrency limit.
 * Uses Promise.allSettled with batching to avoid API rate limits.
 */
export async function generateAllPanels(opts: {
  frames: PanelGenFrame[];
  gridImageUrl: string;
  anchors: PanelGenAnchor[];
  characters: PanelGenCharacter[];
  scenes: PanelGenScene[];
  concurrency?: number;
}): Promise<GeneratedPanel[]> {
  const { frames, gridImageUrl, anchors, characters, scenes, concurrency = 3 } = opts;

  console.log(`[PanelGen] Generating ${frames.length} individual panels (concurrency: ${concurrency})...`);

  // Create all panel generation tasks
  const tasks = frames.map((frame, i) => ({
    frame,
    localIndex: i + 1,
  }));

  const results: GeneratedPanel[] = new Array(frames.length);

  // Process in batches of `concurrency`
  for (let batchStart = 0; batchStart < tasks.length; batchStart += concurrency) {
    const batch = tasks.slice(batchStart, batchStart + concurrency);
    console.log(`[PanelGen] Batch ${Math.floor(batchStart / concurrency) + 1}: panels ${batch.map(t => t.localIndex).join(', ')}`);

    const batchResults = await Promise.allSettled(
      batch.map(task =>
        generateSinglePanelWithRetry({
          frame: task.frame,
          localIndex: task.localIndex,
          totalPanelsInPage: frames.length,
          gridImageUrl,
          anchors,
          characters,
          scenes,
          maxRetries: 2,
        })
      )
    );

    // Store results in order
    for (let j = 0; j < batchResults.length; j++) {
      const idx = batchStart + j;
      const settled = batchResults[j];
      if (settled.status === 'fulfilled') {
        results[idx] = settled.value;
      } else {
        results[idx] = {
          frameIndex: tasks[idx].frame.index,
          imageUrl: null,
          prompt: '',
          error: settled.reason?.message || String(settled.reason),
        };
      }
    }

    // Brief delay between batches
    if (batchStart + concurrency < tasks.length) {
      await new Promise(r => setTimeout(r, 1000));
    }
  }

  const successCount = results.filter(r => r.imageUrl).length;
  const failCount = results.filter(r => r.error).length;
  console.log(`[PanelGen] Done: ${successCount} succeeded, ${failCount} failed out of ${frames.length}`);

  return results;
}

/**
 * Helper: get human-readable shot type description for prompt
 */
function getShotTypeDescription(shotType: string): string {
  const map: Record<string, string> = {
    'EWS': 'Extreme Wide Shot — vast landscape, tiny subjects',
    'WS': 'Wide Shot — full environment with subjects visible',
    'FS': 'Full Shot — full body of subject visible',
    'MWS': 'Medium Wide Shot — subject from knees up',
    'MS': 'Medium Shot — subject from waist up',
    'MCU': 'Medium Close-Up — subject from chest up',
    'CU': 'Close-Up — face or important detail fills the frame',
    'ECU': 'Extreme Close-Up — eyes, hands, or tiny detail',
    'OTS': 'Over-the-Shoulder — shot from behind one character looking at another',
    'POV': 'Point of View — camera shows what the character sees',
    'HA': 'High Angle — camera looks down at subject',
    'LA': 'Low Angle — camera looks up at subject',
    'DA': 'Dutch Angle — tilted camera for tension',
    'AE': 'Aerial/Drone — bird\'s eye view',
    'INS': 'Insert Shot — close-up of a specific object or detail',
  };
  return map[shotType] || shotType;
}
