/**
 * Panel Generator - generates individual panel images one by one.
 * 
 * Flow:
 * 1. Takes the full Grid image (generated by Gemini) as style/composition reference
 * 2. Takes Anchor images (character/scene) for consistency
 * 3. Generates each panel individually with a focused prompt
 * 4. Returns panel image URLs
 */

import { generateImage } from "./_core/imageGeneration";
import { logInfo, logError } from "./appLogger";

export interface PanelGenFrame {
  index: number;         // 1-based frame index
  shotType: string;
  duration: number;
  description: string;
  cameraMovement: string;
}

export interface PanelGenAnchor {
  anchorType: string;    // "character" | "scene"
  name: string;
  description: string | null;
  prompt: string | null;
  imageUrl: string | null;
}

export interface PanelGenCharacter {
  name: string;
  description: string;
  anchorPrompt?: string;
}

export interface PanelGenScene {
  name: string;
  description: string;
  anchorPrompt?: string;
}

export interface GeneratedPanel {
  frameIndex: number;    // 1-based
  imageUrl: string | null;
  prompt: string;
  error?: string;
}

/**
 * Generate a single panel image.
 * References: Grid overview image + character/scene anchors.
 */
export async function generateSinglePanel(opts: {
  frame: PanelGenFrame;
  localIndex: number;          // 1-based index within the page (1-6)
  totalPanelsInPage: number;   // total panels in this page
  gridImageUrl: string;        // Full grid image for style reference
  anchors: PanelGenAnchor[];
  characters: PanelGenCharacter[];
  scenes: PanelGenScene[];
}): Promise<GeneratedPanel> {
  const { frame, localIndex, totalPanelsInPage, gridImageUrl, anchors, characters, scenes } = opts;

  try {
    // Build ordered reference images
    const orderedImages: Array<{ url: string }> = [];
    const imageDescriptions: string[] = [];
    let imgIdx = 1;

    // Image #1: The full Grid image as style/composition reference
    orderedImages.push({ url: gridImageUrl });
    imageDescriptions.push(
      `Image #${imgIdx}: FULL STORYBOARD GRID. This is the complete storyboard overview. ` +
      `Your task is to generate panel #${localIndex} (out of ${totalPanelsInPage}) from this grid as a standalone high-resolution image. ` +
      `Match the exact visual style, color grading, lighting, and character appearance from this grid.`
    );
    imgIdx++;

    // Character anchor images
    const charAnchors = anchors.filter(a => a.anchorType === 'character' && a.imageUrl?.startsWith('http'));
    for (const ca of charAnchors) {
      orderedImages.push({ url: ca.imageUrl! });
      const charData = characters.find(c => c.name === ca.name);
      imageDescriptions.push(
        `Image #${imgIdx}: CHARACTER "${ca.name}" reference. ${ca.prompt || charData?.description || ca.description || 'See reference image'}`
      );
      imgIdx++;
    }

    // Scene anchor images
    const sceneAnchors = anchors.filter(a => a.anchorType === 'scene' && a.imageUrl?.startsWith('http'));
    for (const sa of sceneAnchors) {
      orderedImages.push({ url: sa.imageUrl! });
      const sceneData = scenes.find(s => s.name === sa.name);
      imageDescriptions.push(
        `Image #${imgIdx}: SCENE "${sa.name}" reference. ${sa.prompt || sceneData?.description || sa.description || 'See reference image'}`
      );
      imgIdx++;
    }

    // Build character appearance block
    const charAppearanceLines = charAnchors.map(ca => {
      const charData = characters.find(c => c.name === ca.name);
      return `- "${ca.name}": ${ca.prompt || charData?.description || ca.description || 'See reference image'}`;
    }).join('\n');

    // Build the prompt
    const prompt = `I am providing ${orderedImages.length} reference images:

${imageDescriptions.join('\n')}

YOUR TASK: Generate a single high-resolution cinematic image for Panel #${localIndex} of the storyboard.

PANEL DESCRIPTION:
- Shot type: ${frame.shotType}
- Duration: ${frame.duration}s
- Camera movement: ${frame.cameraMovement}
- Scene: ${frame.description}

CRITICAL REQUIREMENTS:
1. This is a SINGLE standalone image, NOT a grid. Output exactly ONE image.
2. Match the visual style, color palette, and lighting from the full storyboard grid (Image #1).
3. The characters MUST look EXACTLY like the reference photos — same face, ethnicity, hair, clothing.
${charAppearanceLines ? `\nCHARACTER APPEARANCE:\n${charAppearanceLines}` : ''}

SHOT COMPOSITION:
- Frame the shot as a ${frame.shotType} (${getShotTypeDescription(frame.shotType)})
- Camera: ${frame.cameraMovement}
- Capture the specific moment described: ${frame.description}

STYLE:
- Photorealistic cinematic quality (ARRI Alexa / RED camera look)
- Cinematic lighting matching the mood of the scene
- Natural skin textures, realistic environments, atmospheric depth
- NO text, NO labels, NO watermarks, NO borders on the image`;

    console.log(`[PanelGen] Generating panel ${localIndex}/${totalPanelsInPage} (Frame #${frame.index}): ${frame.shotType}`);

    const { url: imageUrl } = await generateImage({
      prompt,
      originalImages: orderedImages,
    });

    logInfo("panel_gen", `Panel ${localIndex} generated successfully`, {
      details: { frameIndex: frame.index, localIndex, shotType: frame.shotType, hasImage: !!imageUrl },
    }).catch(() => {});

    return {
      frameIndex: frame.index,
      imageUrl: imageUrl || null,
      prompt,
    };
  } catch (e: any) {
    console.error(`[PanelGen] Panel ${localIndex} (Frame #${frame.index}) failed:`, e?.message || e);
    
    logError("panel_gen", `Panel ${localIndex} generation failed: ${e?.message}`, {
      details: { frameIndex: frame.index, localIndex, error: e?.message },
    }).catch(() => {});

    return {
      frameIndex: frame.index,
      imageUrl: null,
      prompt: '',
      error: e instanceof Error ? e.message : String(e),
    };
  }
}

/**
 * Generate all panels for a grid page sequentially.
 * Sequential to avoid API rate limits and ensure consistent style.
 */
export async function generateAllPanels(opts: {
  frames: PanelGenFrame[];
  gridImageUrl: string;
  anchors: PanelGenAnchor[];
  characters: PanelGenCharacter[];
  scenes: PanelGenScene[];
}): Promise<GeneratedPanel[]> {
  const { frames, gridImageUrl, anchors, characters, scenes } = opts;
  const results: GeneratedPanel[] = [];

  console.log(`[PanelGen] Generating ${frames.length} individual panels...`);

  for (let i = 0; i < frames.length; i++) {
    const frame = frames[i];
    const localIndex = i + 1;

    const result = await generateSinglePanel({
      frame,
      localIndex,
      totalPanelsInPage: frames.length,
      gridImageUrl,
      anchors,
      characters,
      scenes,
    });

    results.push(result);

    // Brief delay between generations to be nice to the API
    if (i < frames.length - 1) {
      await new Promise(r => setTimeout(r, 1000));
    }
  }

  const successCount = results.filter(r => r.imageUrl).length;
  const failCount = results.filter(r => r.error).length;
  console.log(`[PanelGen] Done: ${successCount} succeeded, ${failCount} failed out of ${frames.length}`);

  return results;
}

/**
 * Helper: get human-readable shot type description for prompt
 */
function getShotTypeDescription(shotType: string): string {
  const map: Record<string, string> = {
    'EWS': 'Extreme Wide Shot — vast landscape, tiny subjects',
    'WS': 'Wide Shot — full environment with subjects visible',
    'FS': 'Full Shot — full body of subject visible',
    'MWS': 'Medium Wide Shot — subject from knees up',
    'MS': 'Medium Shot — subject from waist up',
    'MCU': 'Medium Close-Up — subject from chest up',
    'CU': 'Close-Up — face or important detail fills the frame',
    'ECU': 'Extreme Close-Up — eyes, hands, or tiny detail',
    'OTS': 'Over-the-Shoulder — shot from behind one character looking at another',
    'POV': 'Point of View — camera shows what the character sees',
    'HA': 'High Angle — camera looks down at subject',
    'LA': 'Low Angle — camera looks up at subject',
    'DA': 'Dutch Angle — tilted camera for tension',
    'AE': 'Aerial/Drone — bird\'s eye view',
    'INS': 'Insert Shot — close-up of a specific object or detail',
  };
  return map[shotType] || shotType;
}
