// Seed data for rule chapters from 分镜设计终极规则手册
export const RULE_CHAPTERS_SEED = [
  {
    chapterNumber: 1,
    title: "通用分镜基础法则",
    category: "universal" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "每个镜头只传达一个核心信息", severity: "critical" },
      { type: "do", text: "保持180度轴线规则，除非有意打破", severity: "critical" },
      { type: "do", text: "建立镜头（Establishing Shot）放在场景开头", severity: "warning" },
      { type: "dont", text: "不要在同一场景中无理由跳轴", severity: "critical" },
      { type: "dont", text: "不要连续使用相同景别超过3个镜头", severity: "warning" },
      { type: "do", text: "遵循视线匹配原则", severity: "critical" },
      { type: "do", text: "动作匹配剪辑点保持连贯", severity: "warning" },
    ],
    ruleCount: 7,
  },
  {
    chapterNumber: 2,
    title: "景别使用规范",
    category: "universal" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "远景(EWS)用于建立环境、展示规模", severity: "info" },
      { type: "do", text: "全景(WS)展示角色与环境的关系", severity: "info" },
      { type: "do", text: "中景(MS)适合对话和日常动作", severity: "info" },
      { type: "do", text: "特写(CU)传达情感和关键细节", severity: "info" },
      { type: "do", text: "景别变化应该有节奏感，避免单调", severity: "warning" },
      { type: "dont", text: "不要在动作场景中过多使用静态特写", severity: "warning" },
      { type: "do", text: "插入镜头(INS)用于强调关键道具或细节", severity: "info" },
    ],
    ruleCount: 7,
  },
  {
    chapterNumber: 3,
    title: "运镜技巧",
    category: "universal" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "推镜头(Push In)用于增加紧张感或聚焦", severity: "info" },
      { type: "do", text: "拉镜头(Pull Out)用于揭示环境或制造距离感", severity: "info" },
      { type: "do", text: "横摇(Pan)跟随角色移动或展示空间", severity: "info" },
      { type: "do", text: "跟拍(Tracking)保持与角色同步运动", severity: "info" },
      { type: "dont", text: "不要无目的地使用运镜，每次运镜都要有叙事理由", severity: "critical" },
      { type: "dont", text: "不要在同一镜头中混合多种运镜方式", severity: "warning" },
      { type: "do", text: "手持摄影增加纪实感和紧迫感", severity: "info" },
    ],
    ruleCount: 7,
  },
  {
    chapterNumber: 4,
    title: "构图法则",
    category: "universal" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "使用三分法构图作为基础", severity: "warning" },
      { type: "do", text: "给角色留出视线方向的空间(Lead Room)", severity: "critical" },
      { type: "do", text: "给运动方向留出空间", severity: "critical" },
      { type: "do", text: "利用前景元素增加画面层次", severity: "info" },
      { type: "dont", text: "不要让角色头部被画面顶部截断(Headroom)", severity: "warning" },
      { type: "do", text: "对称构图用于庄严、稳定的场景", severity: "info" },
      { type: "do", text: "引导线构图引导观众视线", severity: "info" },
    ],
    ruleCount: 7,
  },
  {
    chapterNumber: 5,
    title: "追逐场景专属规则",
    category: "scene_specific" as const,
    applicableL2Ids: ["narrative.chase"],
    rules: [
      { type: "do", text: "开场用远景建立追逐空间", severity: "critical" },
      { type: "do", text: "交替展示追逐者和被追者", severity: "critical" },
      { type: "do", text: "随着追逐升级，逐渐缩短镜头时长", severity: "warning" },
      { type: "do", text: "使用低角度拍摄增加速度感", severity: "info" },
      { type: "dont", text: "不要在追逐中使用过长的静态镜头", severity: "critical" },
      { type: "dont", text: "不要在车内追逐镜头中正面特写拍摄司机", severity: "critical" },
      { type: "do", text: "加入环境互动（跨越障碍、转弯等）增加动态", severity: "warning" },
      { type: "do", text: "使用跟拍和手持增加临场感", severity: "warning" },
    ],
    ruleCount: 8,
  },
  {
    chapterNumber: 6,
    title: "对话场景专属规则",
    category: "scene_specific" as const,
    applicableL2Ids: ["narrative.dialogue"],
    rules: [
      { type: "do", text: "建立镜头展示对话环境和人物关系", severity: "critical" },
      { type: "do", text: "使用正反打(Shot/Reverse Shot)交替展示说话者", severity: "critical" },
      { type: "do", text: "过肩镜头(OTS)保持空间关系", severity: "warning" },
      { type: "do", text: "反应镜头展示听者的情绪变化", severity: "warning" },
      { type: "dont", text: "不要在对话中频繁切换角度", severity: "warning" },
      { type: "do", text: "情感高潮时切到特写", severity: "critical" },
      { type: "do", text: "沉默时使用中景或全景展示肢体语言", severity: "info" },
    ],
    ruleCount: 7,
  },
  {
    chapterNumber: 7,
    title: "动作场景专属规则",
    category: "scene_specific" as const,
    applicableL2Ids: ["narrative.action"],
    rules: [
      { type: "do", text: "动作前用中景或全景建立空间关系", severity: "critical" },
      { type: "do", text: "关键动作用多角度覆盖", severity: "warning" },
      { type: "do", text: "快速剪辑增加节奏感，但保持动作连贯", severity: "critical" },
      { type: "dont", text: "不要在动作高潮时使用远景", severity: "warning" },
      { type: "do", text: "使用插入镜头展示武器、拳头等细节", severity: "info" },
      { type: "do", text: "动作结果用特写强调（伤口、表情）", severity: "warning" },
    ],
    ruleCount: 6,
  },
  {
    chapterNumber: 8,
    title: "悬疑惊悚专属规则",
    category: "scene_specific" as const,
    applicableL2Ids: ["narrative.suspense"],
    rules: [
      { type: "do", text: "使用暗调低光营造氛围", severity: "critical" },
      { type: "do", text: "利用画面留白制造不安感", severity: "warning" },
      { type: "do", text: "缓慢推镜头增加紧张感", severity: "warning" },
      { type: "dont", text: "不要过早揭示悬念元素", severity: "critical" },
      { type: "do", text: "使用倾斜构图(Dutch Angle)表达不安", severity: "info" },
      { type: "do", text: "声音线索可以先于视觉线索出现", severity: "info" },
    ],
    ruleCount: 6,
  },
  {
    chapterNumber: 9,
    title: "浪漫情感专属规则",
    category: "scene_specific" as const,
    applicableL2Ids: ["narrative.romance"],
    rules: [
      { type: "do", text: "使用暖色调和柔光营造浪漫氛围", severity: "warning" },
      { type: "do", text: "双人镜头展示角色间的距离变化", severity: "critical" },
      { type: "do", text: "特写眼神交流传达情感", severity: "critical" },
      { type: "do", text: "使用浅景深突出人物、虚化背景", severity: "warning" },
      { type: "dont", text: "不要在情感高潮时使用远景", severity: "warning" },
    ],
    ruleCount: 5,
  },
  {
    chapterNumber: 10,
    title: "喜剧场景专属规则",
    category: "scene_specific" as const,
    applicableL2Ids: ["narrative.comedy"],
    rules: [
      { type: "do", text: "笑点前的铺垫用中景或全景", severity: "warning" },
      { type: "do", text: "笑点时切到特写捕捉表情", severity: "critical" },
      { type: "do", text: "利用画面外空间制造意外", severity: "info" },
      { type: "dont", text: "不要在喜剧场景中连续使用超过3个广角镜头", severity: "warning" },
      { type: "do", text: "反应镜头是喜剧的关键——展示旁观者的反应", severity: "critical" },
    ],
    ruleCount: 5,
  },
  {
    chapterNumber: 11,
    title: "产品展示专属规则",
    category: "scene_specific" as const,
    applicableL2Ids: ["commercial.product", "commercial.food", "commercial.fashion", "commercial.tech"],
    rules: [
      { type: "do", text: "产品必须在每个镜头中清晰可见", severity: "critical" },
      { type: "do", text: "使用微距/特写展示产品质感和细节", severity: "warning" },
      { type: "do", text: "展示产品在使用场景中的样子", severity: "warning" },
      { type: "dont", text: "不要让产品变形或颜色失真", severity: "critical" },
      { type: "dont", text: "食物展示不要使用俯拍超过2帧", severity: "warning" },
      { type: "do", text: "使用转台或缓慢旋转展示产品全貌", severity: "info" },
    ],
    ruleCount: 6,
  },
  {
    chapterNumber: 12,
    title: "短视频节奏结构",
    category: "technical" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "前3秒必须有强钩子（视觉冲击或悬念）", severity: "critical" },
      { type: "do", text: "15秒视频：钩子(3s) + 发展(7s) + 高潮收尾(5s)", severity: "critical" },
      { type: "do", text: "30秒视频：钩子(3s) + 铺垫(7s) + 发展(10s) + 高潮(7s) + 收尾(3s)", severity: "critical" },
      { type: "dont", text: "不要在前5秒使用节奏缓慢的远景", severity: "warning" },
      { type: "do", text: "高潮点放在视频的60%-75%位置", severity: "warning" },
      { type: "do", text: "结尾留悬念或CTA促进互动", severity: "info" },
    ],
    ruleCount: 6,
  },
  {
    chapterNumber: 13,
    title: "光线与色彩",
    category: "technical" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "保持同一场景内光线方向一致", severity: "critical" },
      { type: "do", text: "使用色温变化暗示时间或情绪转换", severity: "info" },
      { type: "do", text: "高对比度光线适合戏剧性场景", severity: "info" },
      { type: "dont", text: "不要在相邻镜头间出现明显的光线矛盾", severity: "critical" },
      { type: "do", text: "逆光/侧光增加画面层次感", severity: "info" },
    ],
    ruleCount: 5,
  },
  {
    chapterNumber: 14,
    title: "AI视频生成提示词规范",
    category: "ai_prompt" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "通用公式：镜头类型+视角+主体+动作+运镜+光影+材质+特效+渲染+环境交互+过渡", severity: "critical" },
      { type: "do", text: "角色锚点公式：性别年龄+体型+发型发色+服装+面部特征+标志元素", severity: "critical" },
      { type: "do", text: "每个prompt只描述1-3秒的单一动作", severity: "critical" },
      { type: "dont", text: "不要在prompt中包含多个复杂动作", severity: "critical" },
      { type: "do", text: "使用英文撰写prompt以获得更好的生成效果", severity: "warning" },
      { type: "do", text: "明确指定画面比例(16:9, 9:16, 1:1)", severity: "warning" },
      { type: "dont", text: "不要使用模糊的描述词如'好看的'、'漂亮的'", severity: "warning" },
      { type: "do", text: "指定具体的光线条件而非笼统的'好光线'", severity: "warning" },
    ],
    ruleCount: 8,
  },
  {
    chapterNumber: 15,
    title: "Grid生成技术规范",
    category: "technical" as const,
    applicableL2Ids: null,
    rules: [
      { type: "do", text: "在prompt中明确指定EXACTLY N panels的精确数量", severity: "critical" },
      { type: "do", text: "使用空白网格模板作为参考确保面板大小均匀", severity: "critical" },
      { type: "do", text: "使用Triple Reference方法：空白网格+风格参考+角色锚点", severity: "critical" },
      { type: "dont", text: "不要让AI自由决定面板数量和布局", severity: "critical" },
      { type: "do", text: "15秒视频使用2×3或2×4布局(6-8帧)", severity: "warning" },
      { type: "do", text: "30秒视频使用3×4或3×5布局(10-15帧)", severity: "warning" },
      { type: "do", text: "每个面板应该是独立的完整构图", severity: "warning" },
    ],
    ruleCount: 7,
  },
];
